(function(){
const URL='https://covrlgwobcolovrznnyk.supabase.co';
const KEY='sb_publishable_SxwNyOAxcq55BnEpjHCyow_MsbSUisX';
let session=JSON.parse(localStorage.getItem('comoara-auth')||'null');
const $=id=>document.getElementById(id);
function authHeaders(extra={}){return {'apikey':KEY,'Authorization':'Bearer '+(session?.access_token||KEY),'Content-Type':'application/json',...extra}}
async function api(path,opt={}){const r=await fetch(URL+path,{...opt,headers:{...authHeaders(),...(opt.headers||{})}});const txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{}if(!r.ok)throw new Error(d?.msg||d?.message||d?.error_description||'Eroare');return d}
function setMsg(t,err=false){const e=$('authMsg');if(e){e.textContent=t;e.style.color=err?'#a32d2d':'#2e7d52'}}
function renderAuth(){const logged=!!session?.access_token;$('authGuest').style.display=logged?'none':'block';$('authUser').style.display=logged?'block':'none';$('accountNav').textContent=logged?'Contul meu':'Conectare';if(logged){const n=session.user?.user_metadata?.display_name||session.user?.email||'Contul meu';$('accountName').textContent=n;$('accountEmail').textContent=session.user?.email||'';loadAccountData();}}
async function signup(){const name=$('signupName').value.trim(),email=$('signupEmail').value.trim(),password=$('signupPassword').value;if(name.length<2)return setMsg('Scrie numele tău.',true);if(password.length<6)return setMsg('Parola trebuie să aibă cel puțin 6 caractere.',true);try{setMsg('Creăm contul…');await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password,data:{display_name:name}})});setMsg('Cont creat. Verifică emailul și apasă linkul de confirmare, apoi conectează-te.')}catch(e){setMsg(e.message,true)}}
async function login(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;try{setMsg('Conectare…');const d=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});session=d;localStorage.setItem('comoara-auth',JSON.stringify(d));setMsg('Te-ai conectat. ✅');renderAuth()}catch(e){setMsg('Nu am putut face conectarea: '+e.message,true)}}
async function logout(){try{await api('/auth/v1/logout',{method:'POST'})}catch{}session=null;localStorage.removeItem('comoara-auth');renderAuth();setMsg('Te-ai deconectat.')}
async function rest(path,opt={}){return api('/rest/v1/'+path,opt)}
async function loadAccountData(){if(!session)return;try{const [notes,favs,state]=await Promise.all([rest('bible_notes?select=id,book,chapter,verse,note,created_at&order=created_at.desc'),rest('favorite_verses?select=id,book,chapter,verse,created_at&order=created_at.desc'),rest('reading_state?select=book,chapter&limit=1')]);$('notesCount').textContent=notes.length;$('favoritesCount').textContent=favs.length;$('savedNotes').innerHTML=notes.length?notes.map(n=>`<div class="savedItem"><b>📝 ${esc(n.book)} ${n.chapter}${n.verse?':'+n.verse:''}</b><p>${esc(n.note)}</p><button onclick="window.deleteBibleNote('${n.id}')">Șterge</button></div>`).join(''):'<p class="muted">Nu ai încă notițe salvate.</p>';$('savedFavorites').innerHTML=favs.length?favs.map(f=>`<div class="savedItem"><b>❤️ ${esc(f.book)} ${f.chapter}:${f.verse}</b><button onclick="window.deleteFavorite('${f.id}')">Șterge</button></div>`).join(''):'<p class="muted">Nu ai încă versete favorite.</p>';if(state?.[0]){$('lastReading').textContent=state[0].book+' '+state[0].chapter;$('continueFree').dataset.book=state[0].book;$('continueFree').dataset.chapter=state[0].chapter;}}catch(e){console.warn(e)}}
window.deleteBibleNote=async id=>{if(!session)return;await rest('bible_notes?id=eq.'+id,{method:'DELETE'});loadAccountData()};
window.deleteFavorite=async id=>{if(!session)return;await rest('favorite_verses?id=eq.'+id,{method:'DELETE'});loadAccountData()};
window.saveBibleNote=async(book,chapter,verse)=>{if(!session){location.hash='cont';setMsg('Conectează-te pentru a păstra notițele.',true);return}const note=prompt(`Notiță pentru ${book} ${chapter}:${verse}`);if(!note?.trim())return;await rest('bible_notes',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({user_id:session.user.id,book,chapter,verse,note:note.trim()})});loadAccountData();alert('Notița a fost salvată. ✅')};
window.toggleFavorite=async(book,chapter,verse)=>{if(!session){location.hash='cont';setMsg('Conectează-te pentru a salva versete favorite.',true);return}const q=`favorite_verses?user_id=eq.${session.user.id}&book=eq.${encodeURIComponent(book)}&chapter=eq.${chapter}&verse=eq.${verse}&select=id`;const found=await rest(q);if(found.length)await rest('favorite_verses?id=eq.'+found[0].id,{method:'DELETE'});else await rest('favorite_verses',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({user_id:session.user.id,book,chapter,verse})});loadAccountData();alert(found.length?'Scos din favorite.':'Salvat la favorite. ❤️')};
async function saveReading(book,chapter){if(!session)return;await rest('reading_state?on_conflict=user_id',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:session.user.id,book,chapter,updated_at:new Date().toISOString()})}).catch(()=>{})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.openFreeBible=async function(bookName,chapter){const code=BOOKMAP[bookName];if(!code)return;const overlay=document.createElement('div');overlay.className='readerOverlay';overlay.innerHTML=`<div class="readerPanel"><div class="readerTop"><h2>${esc(bookName)} ${chapter}</h2><button class="readerClose">← Înapoi</button></div><div class="readerBody"><div id="freeContent" class="readerLoading">Se încarcă Biblia…</div></div></div>`;document.body.appendChild(overlay);document.body.style.overflow='hidden';overlay.querySelector('.readerClose').onclick=()=>{overlay.remove();document.body.style.overflow=''};try{const bible=await loadRccv(),ch=bible[code]?.[String(chapter)];if(!ch)throw new Error('Capitolul nu a fost găsit.');const verses=Object.entries(ch).filter(([,t])=>String(t).trim()).sort((a,b)=>+a[0]-+b[0]);overlay.querySelector('#freeContent').className='';overlay.querySelector('#freeContent').innerHTML=`<article class="chapter"><h3>${esc(bookName)} ${chapter}</h3>${verses.map(([n,t])=>`<div class="freeVerse"><p class="verse"><span class="verseNum">${n}</span>${esc(t)}</p><div class="verseActions"><button onclick="toggleFavorite('${esc(bookName).replace(/'/g,"\\'")}',${chapter},${n})">♡ Favorite</button><button onclick="saveBibleNote('${esc(bookName).replace(/'/g,"\\'")}',${chapter},${n})">📝 Notiță</button></div></div>`).join('')}</article>`;saveReading(bookName,chapter);loadAccountData()}catch(e){overlay.querySelector('#freeContent').innerHTML='<div class="readerError">'+esc(e.message)+'</div>'}}
function setupFreeReader(){const sel=$('freeBook');Object.keys(BOOKMAP).forEach(b=>{const o=document.createElement('option');o.value=o.textContent=b;sel.appendChild(o)});$('openFreeBible').onclick=()=>openFreeBible(sel.value,Math.max(1,parseInt($('freeChapter').value)||1));$('continueFree').onclick=()=>{const b=$('continueFree').dataset.book||'Geneza',c=+$('continueFree').dataset.chapter||1;openFreeBible(b,c)}}
$('signupBtn').onclick=signup;$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;setupFreeReader();renderAuth();
})();
